# Imagen base oficial de MariaDB
FROM mariadb:10.11

# Variables de entorno
ENV MARIADB_ROOT_PASSWORD=admin123
ENV MARIADB_DATABASE=absentismo_db

# Copiamos el script SQL de creación de tablas
COPY absentismo_mariadb.sql /docker-entrypoint-initdb.d/

# Exponemos el puerto
EXPOSE 3307

# Volumen persistente para los datos
VOLUME /var/lib/mysql
